# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b0e76cdb1e35b9a4ff6386e8b0b762754e79d43c738ff1d512b8ce391f5ad6d71e172614f903bd23522d1afc073c28de16d2228526ee4918b55ed8d7a394ac9

test:
  secret_key_base: 1d287cc1eabfbd5d2ba816c21905c9598112f72ef38ab1b56c2885e8ca602991da99f4b60f022bc22b53fdc89f9382909b5dae59625c3d997a561cce02cb4a92

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
